on:
  push:
      branches:
        - GH-88/CLDV-4/disabling_addons
jobs:
  deploy_cluster_job:
    runs-on: ubuntu-latest
    name: Cluster.dev
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        ref: 'GH-88/CLDV-4/disabling_addons' #CHANGE ME
    - name: Reconcile Clusters
      id: reconcile
      uses: shalb/cluster.dev@v0.3.3
      env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        CLUSTER_CONFIG_PATH: "./.cluster.dev/"
        VERBOSE_LVL: DEBUG
